/*
   Generated by EX4-TO-MQ4 decompiler FREEWARE V4.0.451.1 [-]
   Website: http://www.metaquotes.net
   E-mail : support@metaquotes.net
*/
#property link      "http://www.freescalperindicator.com"

#property indicator_separate_window
#property indicator_minimum -1.0
#property indicator_maximum 1.0
#property indicator_buffers 2
#property indicator_color1 Green
#property indicator_color2 Red

extern int Length = 14;
int gi_80 = 5000;
int gi_84 = 1;
int gi_88 = 1;
double gda_92[];
double gda_96[];
double gda_100[];
double gda_104[];
double gda_108[];
double gda_112[];
double gd_116 = 1.0;
double gd_124 = 2.0;

// E37F0136AA3FFAF149B351F6A4C948E9
int init() {
   SetIndexBuffer(0, gda_92);
   SetIndexBuffer(1, gda_96);
   SetIndexStyle(0, DRAW_HISTOGRAM);
   SetIndexStyle(1, DRAW_HISTOGRAM);
   IndicatorDigits(MarketInfo(Symbol(), MODE_DIGITS));
   string ls_0 = "www.FreeScalperIndicator.com ";
   IndicatorShortName(ls_0);
   SetIndexDrawBegin(0, Length);
   SetIndexDrawBegin(1, Length);
   return (0);
}

// EA2B2676C28C0DB26D39331A336C6B92
int start() {
   int li_8;
   double lda_12[25000];
   double lda_16[25000];
   double lda_20[25000];
   double lda_24[25000];
   for (int li_4 = gi_80; li_4 >= 0; li_4--) {
      gda_92[li_4] = 0;
      gda_96[li_4] = 0;
      gda_100[li_4] = 0;
      gda_104[li_4] = 0;
      gda_108[li_4] = 0;
      gda_112[li_4] = 0;
   }
   for (li_4 = gi_80 - Length - 1; li_4 >= 0; li_4--) {
      lda_12[li_4] = iBands(NULL, 0, Length, gd_124, 0, PRICE_CLOSE, MODE_UPPER, li_4);
      lda_16[li_4] = iBands(NULL, 0, Length, gd_124, 0, PRICE_CLOSE, MODE_LOWER, li_4);
      if (Close[li_4] > lda_12[li_4 + 1]) li_8 = 1;
      if (Close[li_4] < lda_16[li_4 + 1]) li_8 = -1;
      if (li_8 > 0 && lda_16[li_4] < lda_16[li_4 + 1]) lda_16[li_4] = lda_16[li_4 + 1];
      if (li_8 < 0 && lda_12[li_4] > lda_12[li_4 + 1]) lda_12[li_4] = lda_12[li_4 + 1];
      lda_20[li_4] = lda_12[li_4] + (gd_116 - 1.0) / 2.0 * (lda_12[li_4] - lda_16[li_4]);
      lda_24[li_4] = lda_16[li_4] - (gd_116 - 1.0) / 2.0 * (lda_12[li_4] - lda_16[li_4]);
      if (li_8 > 0 && lda_24[li_4] < lda_24[li_4 + 1]) lda_24[li_4] = lda_24[li_4 + 1];
      if (li_8 < 0 && lda_20[li_4] > lda_20[li_4 + 1]) lda_20[li_4] = lda_20[li_4 + 1];
      if (li_8 > 0) {
         if (gi_84 > 0 && gda_92[li_4 + 1] == -1.0) {
            gda_100[li_4] = lda_24[li_4];
            gda_92[li_4] = lda_24[li_4];
            if (gi_88 > 0) {
               gda_92[li_4] = 0.2;
               gda_96[li_4] = EMPTY_VALUE;
            }
         } else {
            gda_92[li_4] = lda_24[li_4];
            if (gi_88 > 0) {
               gda_92[li_4] = 0.2;
               gda_96[li_4] = EMPTY_VALUE;
            }
            gda_100[li_4] = -1;
         }
         if (gi_84 == 2) gda_92[li_4] = 0;
         gda_104[li_4] = -1;
         gda_96[li_4] = -1.0;
         gda_96[li_4] = 0;
         gda_112[li_4] = EMPTY_VALUE;
      }
      if (li_8 < 0) {
         if (gi_84 > 0 && gda_96[li_4 + 1] == -1.0) {
            gda_104[li_4] = lda_20[li_4];
            gda_96[li_4] = lda_20[li_4];
            if (gi_88 > 0) {
               gda_96[li_4] = 0.2;
               gda_92[li_4] = EMPTY_VALUE;
            }
         } else {
            gda_96[li_4] = lda_20[li_4];
            if (gi_88 > 0) {
               gda_96[li_4] = 0.2;
               gda_92[li_4] = EMPTY_VALUE;
            }
            gda_104[li_4] = -1;
         }
         if (gi_84 == 2) gda_96[li_4] = 0;
         gda_100[li_4] = -1;
         gda_92[li_4] = 0;
         gda_108[li_4] = EMPTY_VALUE;
      }
   }
   return (0);
}
